name: Publish Package to npmjs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run test
  build-publish:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run prettier
      - run: npm run eslint
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: "npm run release:${{inputs.version}}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
